// vue/components/application-ui/headings/card-headings/simple.vue
<template>
  <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
    <h3 class="text-base font-semibold leading-6 text-gray-900">Job Postings</h3>
  </div>
</template>

<script setup>
const items = [
  { id: 1, title: 'Back End Developer', type: 'Full-time', department: 'Engineering', location: 'Remote' },
  { id: 2, title: 'Front End Developer', type: 'Full-time', department: 'Engineering', location: 'Remote' },
  { id: 3, title: 'User Interface Designer', type: 'Full-time', department: 'Design', location: 'Remote' },
]
</script>

// react/components/application-ui/headings/card-headings/simple.jsx
const items = [
  { id: 1, title: 'Back End Developer', type: 'Full-time', department: 'Engineering', location: 'Remote' },
  { id: 2, title: 'Front End Developer', type: 'Full-time', department: 'Engineering', location: 'Remote' },
  { id: 3, title: 'User Interface Designer', type: 'Full-time', department: 'Design', location: 'Remote' },
]

export default function Example() {
  return (
    <div className="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
      <h3 className="text-base font-semibold leading-6 text-gray-900">Job Postings</h3>
    </div>
  )
}
